# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines-testing

resources:
  repositories:
    - repository: rust_pipelines
      type: github
      name: xoac/rust-azure-pipelines
      # ref: refs/tags/v0.1.0
      endpoint: ebbflow-test

stages:
- stage: InitialCheck
  displayName: "Quick checks"
  jobs:
  - template: ci/scenarios/check.yml@rust_pipelines
- stage: MultiOsChecks
  displayName: "Multi OS Tests"
  jobs:
  - template: ci/scenarios/test.yml@rust_pipelines
    parameters:
      min_rust_supported: 1.43  # Use first rust version you wanna support
- stage: BuildPackages
  displayName: "Build Distributable Packages"
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job:
    steps:
    - bash: echo "Hello world"
      displayName: 'Run a one-line script'
    - bash: echo "Hello world II"
      displayName: 'Run do something else'
