[package]
name = "ebb-client"
version = "0.1.0"
authors = ["Ryan Gorup <gorup@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio-rustls = "0.12.1"
log = "0.4.8"
rand = "0.7.2"
env_logger = "0.7.1"
clap = "2.33.0"
tokio = { version = "0.2", features = ["full"] }
rustls = "0.16"

[dev-dependencies]
hyper = "0.13"
hostname = "0.2"