[package]
name = "ebb-client"
version = "0.4.0"
authors = ["Ryan Gorup <gorup@users.noreply.github.com>"]
edition = "2018"
readme = "README.md"
keywords = ["ssh", "proxy", "loadbalancer", "tcp", "ebbflow"]
maintenance = { status = "actively-developed" }
license-file = "LICENSE"
homepage = "https://ebbflow.io"
categories = ["network-programming", "command-line-utilities", "web-programming"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ebbflow"
path = "src/main.rs"

[dependencies]
futures = "0.3"
tokio-rustls = "0.13"
log = "0.4.8"
rand = { version = "0.7.3", features = ["small_rng"] }
env_logger = "0.7.1"
clap = "2.33.0"
tokio = { version = "0.2", features = ["full"] }
rustls = "0.17"
hostname = "0.3"
simplelog = "0.7.4"

[dev-dependencies]
hyper = "0.13"
hostname = "0.3"