on:
  push:
    branches:
      - master

name: Continuous Integration

jobs:
  opensuseleaprpmbuild:
    runs-on: ubuntu-latest
    name: OpensuseLeapRpm
    steps:
    - uses: actions/checkout@v2
    - name: BuildRpm
      id: buildrpm
      uses: ebbflow-io/cargo-rpm-amd64-opensuseleap@master
      with:
        dockertag: latest
    - name: Upload RPM Artifact
      uses: actions/upload-artifact@v2
      with:
        name: opensuserpm
        path: ./target/x86_64-unknown-linux-musl/release/rpmbuild/RPMS/x86_64/*
